name: 'Populate PR in Changelog'
description: 'Populate GitHub Pull Request number in Changelog'
branding:
  icon: 'hash'
  color: 'blue'
runs:
  using: "composite"
  steps:
  - name: Check out repository code
    uses: actions/checkout@v3
    with:
      ref: ${{github.event.pull_request.head.ref}}
      repository: ${{github.event.pull_request.head.repo.full_name}}
  - name: Replacing the <PR_NUMBER> variable
    run: |
      sed -i -e "s/#<PR_NUMBER>/#${{ github.event.pull_request.number }}/" CHANGES.md
    shell: bash
  - uses: getsentry/action-git-diff-suggestions@main
    with:
      message: 'Populate-Changelog-Action'
